price_raw:
LOAD * INLINE [
price_id, individual_price, regular_price, invoice_price
1, 100, 150, 100
2, 1, 200, 1
3, 95,100,120
];

price:
LOAD
    *,
    IF(individual_price = 1,
        'Promocja 1 zł',
        IF(discount_percent = 5,
            '5 % znizki',
            'Inna promocja'
        )
    ) AS promo_type,

    IF(invoice_price = individual_price, 1, 0) AS validation_result;

LOAD
    *,
    ROUND((1 - individual_price / regular_price), 0.01) * 100 AS discount_percent
RESIDENT price_raw;

DROP TABLE price_raw;
